### ISSUE TITLE
Default spring.gsp.tldScanPattern by classpath

### ISSUE THREAD

**Issue by rwinch** [grails/grails-boot#2]
One of the things that is nice about Spring Boot is that it will automatically make reasonable defaults. It would be nice if spring.gsp.tldScanPattern could be defaulted to include Spring's TLD (and possibly other TLD on the classpath).

**Comment by rameshkt** [comment]
I am integrating OWASP CSRF Guard into a Grails 6.2.0 application. The issue I have is the csrf tags are not recognized in the .gsp files. I followed the instructions in the Grails Tag Libraries documentation and added the tldScanPattern in application.yml.
The .tld file for the csrf tags are inside META-INF/tags. IF I add the path tp tldScanPattern I get this error:- ServletContext resource [/META-INF/tags/] cannot be resolved to URL because it does not exist.
Could I get some guidance on this?
Regards
